//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalenderMonth
    {
        public int Id { get; set; }
        public System.DateTime Month { get; set; }
    
        public virtual MonthlyReport MonthlyReport { get; set; }
    }
}
