//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendanceStudent
    {
        public int DateId { get; set; }
        public int StudentId { get; set; }
        public string AttendanceStatus { get; set; }
    
        public virtual DateKeeper DateKeeper { get; set; }
        public virtual Student Student { get; set; }
    }
}
