//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamBySubject
    {
        public int ExamId { get; set; }
        public int SubjectId { get; set; }
        public int TotalMarks { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
